import { Layout } from "@/components/layout/Layout";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

const DisclaimerPage = () => {
  return (
    <Layout>
      <div className="min-h-screen bg-background py-16">
        <div className="container mx-auto px-4 max-w-4xl">
          <Button variant="ghost" className="mb-6" asChild>
            <Link to="/"><ArrowLeft className="h-4 w-4 mr-2" />Back to Home</Link>
          </Button>

          <h1 className="text-4xl font-bold text-foreground mb-8">Legal Disclaimer</h1>

          <div className="space-y-8 text-foreground/90">
            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">Not legal advice</h2>
              <p>
                LegallyAI is a technology platform, not a law firm. Content, chat answers, and documents produced by
                the Service are for general informational purposes only and are not legal advice.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">No attorney-client relationship</h2>
              <p>
                Using LegallyAI does not create an attorney-client relationship between you and LegallyAI or any
                attorney. Nothing you submit to the Service creates a duty of confidentiality owed by an attorney.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">AI-generated content</h2>
              <p>
                Responses and documents are generated by artificial intelligence and may be incomplete, outdated, or
                wrong. Review every output carefully. Have a licensed attorney in your jurisdiction review any
                document before you sign, file, or rely on it.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">Unauthorized practice of law</h2>
              <p>
                The Service does not practice law and is not a substitute for a lawyer. Attorneys who use the Service
                remain solely responsible for their professional judgment, work product, and compliance with the
                rules of professional conduct that apply to them.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">Laws vary</h2>
              <p>
                Laws differ by state, country, and court, and they change. A document or answer that is suitable in
                one jurisdiction may be invalid or inappropriate in another.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">No guarantee of outcomes</h2>
              <p>
                We do not guarantee any legal result, the accuracy of any prediction or analysis, or that a document
                will be accepted by any court or agency.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">Emergencies</h2>
              <p>
                If you are in immediate danger, call your local emergency number. If you have an urgent legal
                deadline, contact a licensed attorney right away.
              </p>
            </section>

            <p className="text-sm text-muted-foreground">
              See also our <Link to="/terms" className="underline">Terms of Service</Link> and{" "}
              <Link to="/privacy" className="underline">Privacy Policy</Link>.
            </p>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default DisclaimerPage;
