import { useState } from "react";
import { Layout } from "@/components/layout/Layout";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { 
  FileText, Download, Printer, Copy, CheckCircle, 
  Loader2, Sparkles, AlertCircle, Lock
} from "lucide-react";
import { toast } from "sonner";

const documentTypes = [
  "NDA (Non-Disclosure Agreement)",
  "Employment Contract",
  "Freelancer Agreement",
  "LLC Operating Agreement",
  "Lease Agreement",
  "Service Agreement",
  "Will & Testament",
  "Power of Attorney",
  "Promissory Note",
  "Partnership Agreement",
];

export default function GeneratePage() {
  const [prompt, setPrompt] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedDoc, setGeneratedDoc] = useState<string | null>(null);
  const [isPaid, setIsPaid] = useState(false);

  const handleGenerate = async () => {
    if (!prompt.trim()) {
      toast.error("Please describe your legal document needs");
      return;
    }

    setIsGenerating(true);
    
    // Simulate AI generation (will be replaced with real AI when backend is connected)
    setTimeout(() => {
      const mockDocument = `
LEGAL DOCUMENT

Generated for: ${prompt}

---

This is a preview of your legal document. The full document includes:

• Complete legal clauses and provisions
• State-specific language (US Law 2025)
• Professional formatting
• Customizable sections
• Signature blocks

---

DISCLAIMER: This document is generated by AI for informational purposes. 
Consult with a licensed attorney before signing any legal document.

---

To access the full document with all clauses, please upgrade to unlock.
      `.trim();

      setGeneratedDoc(mockDocument);
      setIsGenerating(false);
      toast.success("Document preview generated!");
    }, 2000);
  };

  const handleUnlock = () => {
    toast.info("Payment integration will be available once backend is connected");
  };

  const handleDownload = () => {
    if (!isPaid) {
      toast.error("Please unlock the full document first");
      return;
    }
    toast.success("Document downloaded!");
  };

  const handleCopy = () => {
    if (generatedDoc) {
      navigator.clipboard.writeText(generatedDoc);
      toast.success("Copied to clipboard!");
    }
  };

  return (
    <Layout>
      <section className="py-12 md:py-20 bg-background min-h-screen">
        <div className="container mx-auto px-4">
          {/* Header */}
          <div className="text-center mb-12">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-legal-gold/10 border border-legal-gold/30 mb-6">
              <Sparkles className="h-4 w-4 text-legal-gold" />
              <span className="text-sm font-medium text-legal-gold">AI-Powered</span>
            </div>
            <h1 className="font-display text-3xl md:text-4xl font-bold text-foreground mb-4">
              Generate Legal Documents
            </h1>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Describe your legal needs in plain English. Our AI will generate a professional, 
              legally-accurate document in seconds.
            </p>
          </div>

          <div className="grid lg:grid-cols-2 gap-8 max-w-6xl mx-auto">
            {/* Input Section */}
            <div className="space-y-6">
              <div className="p-6 rounded-2xl bg-card border border-border shadow-card">
                <h2 className="font-display text-xl font-semibold text-foreground mb-4 flex items-center gap-2">
                  <FileText className="h-5 w-5 text-legal-gold" />
                  Describe Your Document
                </h2>

                <Textarea
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  placeholder="Example: Create an NDA for a California startup hiring a Texas-based developer. Include non-compete clause and intellectual property protection..."
                  className="min-h-[200px] mb-4 resize-none text-base"
                />

                <Button
                  onClick={handleGenerate}
                  disabled={isGenerating || !prompt.trim()}
                  variant="gold"
                  size="lg"
                  className="w-full"
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="h-5 w-5 animate-spin" />
                      Generating Document...
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-5 w-5" />
                      Generate Document
                    </>
                  )}
                </Button>
              </div>

              {/* Quick Templates */}
              <div className="p-6 rounded-2xl bg-muted border border-border">
                <h3 className="font-semibold text-foreground mb-4">Popular Templates</h3>
                <div className="flex flex-wrap gap-2">
                  {documentTypes.slice(0, 6).map((type) => (
                    <button
                      key={type}
                      onClick={() => setPrompt(`Create a ${type} for my business`)}
                      className="px-3 py-2 text-sm rounded-lg bg-background border border-border hover:border-legal-gold/50 hover:bg-legal-gold/5 transition-colors"
                    >
                      {type}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* Output Section */}
            <div className="space-y-6">
              <div className="p-6 rounded-2xl bg-card border border-border shadow-card min-h-[400px]">
                <div className="flex items-center justify-between mb-4">
                  <h2 className="font-display text-xl font-semibold text-foreground">
                    Generated Document
                  </h2>
                  {generatedDoc && (
                    <button
                      onClick={handleCopy}
                      className="p-2 rounded-lg hover:bg-muted transition-colors"
                      title="Copy to clipboard"
                    >
                      <Copy className="h-4 w-4 text-muted-foreground" />
                    </button>
                  )}
                </div>

                {!generatedDoc ? (
                  <div className="flex flex-col items-center justify-center h-64 text-center">
                    <FileText className="h-16 w-16 text-muted-foreground/30 mb-4" />
                    <p className="text-muted-foreground">
                      Your generated document will appear here
                    </p>
                  </div>
                ) : (
                  <div className="prose prose-sm max-w-none">
                    <pre className="whitespace-pre-wrap text-sm text-foreground bg-muted p-4 rounded-lg font-mono">
                      {generatedDoc}
                    </pre>
                  </div>
                )}
              </div>

              {generatedDoc && !isPaid && (
                <div className="p-6 rounded-2xl bg-gradient-to-br from-legal-gold/10 to-amber-500/10 border border-legal-gold/30">
                  <div className="flex items-start gap-4">
                    <div className="p-2 rounded-lg bg-legal-gold/20">
                      <Lock className="h-6 w-6 text-legal-gold" />
                    </div>
                    <div className="flex-1">
                      <h3 className="font-semibold text-foreground mb-2">
                        Unlock Full Document
                      </h3>
                      <p className="text-sm text-muted-foreground mb-4">
                        Get the complete legal document with all clauses, state-specific language, 
                        and professional formatting for just $29.
                      </p>
                      <Button onClick={handleUnlock} variant="gold" className="w-full sm:w-auto">
                        Pay $29 – Unlock Now
                      </Button>
                    </div>
                  </div>
                </div>
              )}

              {generatedDoc && isPaid && (
                <div className="flex gap-3">
                  <Button onClick={handleDownload} variant="gold" className="flex-1">
                    <Download className="h-4 w-4" />
                    Download PDF
                  </Button>
                  <Button variant="outline" className="flex-1">
                    <Printer className="h-4 w-4" />
                    Print
                  </Button>
                </div>
              )}
            </div>
          </div>

          {/* Disclaimer */}
          <div className="mt-12 max-w-3xl mx-auto">
            <div className="flex items-start gap-3 p-4 rounded-lg bg-muted border border-border">
              <AlertCircle className="h-5 w-5 text-muted-foreground shrink-0 mt-0.5" />
              <p className="text-sm text-muted-foreground">
                <strong>Disclaimer:</strong> LegallyAI generates documents using AI technology 
                for informational purposes only. This is not legal advice. We recommend consulting 
                with a licensed attorney before signing or relying on any legal document.
              </p>
            </div>
          </div>
        </div>
      </section>
    </Layout>
  );
}
